export const ivrLanguages = {
  en: { label: "English", speechCode: "en-IN" },
  hi: { label: "हिन्दी", speechCode: "hi-IN" },
  kn: { label: "ಕನ್ನಡ", speechCode: "kn-IN" },
  ta: { label: "தமிழ்", speechCode: "ta-IN" },
  te: { label: "తెలుగు", speechCode: "te-IN" },
  ml: { label: "മലയാളം", speechCode: "ml-IN" },
  mr: { label: "मराठी", speechCode: "mr-IN" },
  bn: { label: "বাংলা", speechCode: "bn-IN" },
  gu: { label: "ગુજરાતી", speechCode: "gu-IN" },
  pa: { label: "ਪੰਜਾਬੀ", speechCode: "pa-IN" }
};

export const ivrTranslations = {
  en: {
    title: "AI IVR Helper Assistant",
    assistantReady: "Assistant Ready",
    sayCommand: "Say a command or number",
    selectSpokenLanguage: "Select Spoken Language",
    repeat: "Repeat (0)",
    stopTTS: "Stop Voice",
    close: "Close",
    listening: "Listening... speak now",
    speaking: "Speaking instructions...",
    openingPage: "Opening requested page...",
    easyMode: "Easy Mode",
    trySaying: "Try Saying / Try Matching",
    userInputLabel: "User Said",
    detectedIntentLabel: "Detected",
    aiResponseLabel: "AI Response",
    actionStatusLabel: "Action",
    navigatingStatus: "Navigating...",
    waitingStatus: "Waiting...",
    confirmQuestion: "Do you want to continue? Say yes or no.",
    confidenceLow: "I heard you but I am not sure. Please repeat once.",
    helpText: "You can say jobs, wages, attendance, insurance, support, or a menu number.",
    notUnderstood: "I did not understand. Please say a menu number or say repeat.",
    
    // Menu Keys
    findJobs: "Find Jobs",
    myWorks: "My Works",
    attendanceTracking: "Attendance Tracking",
    wagesManagement: "Wages Tracking",
    healthInsurance: "Health Insurance",
    feedbackRating: "Feedback & Rating",
    chatSupport: "AI Chat Support",
    hireLabour: "Hire Labour",
    manageJobs: "Manage Jobs",
    rentalMarketplace: "Rental Marketplace",
    attendanceManagement: "Attendance Management",
    wagesManagementOwner: "Wages Management",
    overview: "Overview",
    userManagement: "User Management",
    activeJobs: "Active Jobs",
    rentalSystem: "Rental System",
    globalAttendance: "Global Attendance",
    globalWages: "Global Wages",
    profitsLedger: "Profits & Ledger",
    
    // Spoken Audio prompts
    welcomeGreetings: {
      labour: "Welcome to ShramaSetu Labour Portal. Press or say 1 for Find Jobs. 2 for My Works. 3 for Attendance. 4 for Wages. 5 for Insurance. 6 for Feedback. 7 for AI Support. Or 0 to repeat menu.",
      owner: "Welcome to ShramaSetu Owner Portal. Press or say 1 for Hire Labour. 2 for Manage Jobs. 3 for Rental Marketplace. 4 for Attendance. 5 for Wages. 6 for Insurance. 7 for Feedback. 8 for Chat Support. Or 0 to repeat menu.",
      admin: "Welcome to ShramaSetu Admin Portal. Press or say 1 for Overview. 2 for User Management. 3 for Active Jobs. 4 for Rentals. 5 for Attendance. 6 for Wages. 7 for Insurance. 8 for Profits. 9 for Feedback. 10 for Support. Or 0 to repeat menu."
    },
    spokenResponses: {
      findJobs: "Opening Available Job Offers.",
      myWorks: "Opening your active works list.",
      attendance: "Opening attendance tracker.",
      wages: "Showing your wage records.",
      insurance: "Opening insurance dashboard.",
      feedback: "Opening feedback form.",
      support: "Opening AI Chat Support.",
      rentals: "Opening rental marketplace.",
      overview: "Admin System Status dashboard opened. Currently 2 registered users, 1 active job, Firestore server connected.",
      languageChanged: "Language changed to English.",
      notUnderstood: "I did not understand. Please say a menu number or say repeat.",
      repeatMenu: "Repeating menu options."
    }
  },
  hi: {
    title: "एआई आईवीआर सहायक",
    assistantReady: "सहायक तैयार है",
    sayCommand: "एक कमांड या संख्या बोलें",
    selectSpokenLanguage: "बोली जाने वाली भाषा चुनें",
    repeat: "दोहराएं (0)",
    stopTTS: "आवाज बंद करें",
    close: "बंद करें",
    listening: "सुन रहा हूँ... अब बोलें",
    speaking: "निर्देश बोल रहा हूँ...",
    openingPage: "अनुरोधित पृष्ठ खोल रहा हूँ...",
    easyMode: "आसान मोड",
    trySaying: "बोलने का प्रयास करें / मिलान करें",
    userInputLabel: "उपयोगकर्ता ने कहा",
    detectedIntentLabel: "पता चला",
    aiResponseLabel: "एआई प्रतिक्रिया",
    actionStatusLabel: "कार्रवाई",
    navigatingStatus: "नेविगेट कर रहा है...",
    waitingStatus: "प्रतीक्षा में...",
    confirmQuestion: "क्या आप जारी रखना चाहते हैं? हाँ या ना बोलें।",
    confidenceLow: "मैंने सुना लेकिन मुझे यकीन नहीं है। कृपया एक बार फिर बोलें।",
    helpText: "आप नौकरी, मजदूरी, हाजिरी, बीमा, सहायता या मेनू नंबर बोल सकते हैं।",
    notUnderstood: "मुझे समझ नहीं आया। कृपया एक मेनू नंबर बोलें या दोहराएं बोलें।",
    
    findJobs: "नौकरी खोजें",
    myWorks: "मेरा काम",
    attendanceTracking: "हाजिरी ट्रैकिंग",
    wagesManagement: "मजदूरी ट्रैकिंग",
    healthInsurance: "स्वास्थ्य बीमा",
    feedbackRating: "फीडबैक और रेटिंग",
    chatSupport: "एआई चैट सहायता",
    hireLabour: "श्रमिक किराए पर लें",
    manageJobs: "नौकरियां प्रबंधित करें",
    rentalMarketplace: "किराया बाजार",
    attendanceManagement: "हाजिरी प्रबंधन",
    wagesManagementOwner: "मजदूरी प्रबंधन",
    overview: "अवलोकन",
    userManagement: "उपयोगकर्ता प्रबंधन",
    activeJobs: "सक्रिय नौकरियां",
    rentalSystem: "किराया प्रणाली",
    globalAttendance: "वैश्विक हाजिरी",
    globalWages: "वैश्विक मजदूरी",
    profitsLedger: "लाभ और बहीखाता",
    
    welcomeGreetings: {
      labour: "श्रमसेतु श्रमिक पोर्टल पर आपका स्वागत है। नौकरियों के लिए 1 दबाएं या बोलें। मेरे काम के लिए 2। हाजिरी के लिए 3। मजदूरी के लिए 4। बीमा के लिए 5। फीडबैक के लिए 6। एआई सहायता के लिए 7। या मेनू दोहराने के लिए 0 दबाएं।",
      owner: "श्रमसेतु मालिक पोर्टल पर आपका स्वागत है। श्रमिक किराए पर लेने के लिए 1 दबाएं या बोलें। नौकरियां प्रबंधित करने के लिए 2। किराया बाजार के लिए 3। हाजिरी के लिए 4। मजदूरी के लिए 5। बीमा के लिए 6। फीडबैक के लिए 7। चैट सहायता के लिए 8। या मेनू दोहराने के लिए 0 दबाएं।",
      admin: "श्रमसेतु एडमिन पोर्टल पर आपका स्वागत है। अवलोकन के लिए 1 दबाएं या बोलें। उपयोगकर्ता प्रबंधन के लिए 2। सक्रिय नौकरियों के लिए 3। किराये के लिए 4। हाजिरी के लिए 5। मजदूरी के लिए 6। बीमा के लिए 7। लाभ के लिए 8। फीडबैक के लिए 9। सहायता के लिए 10। या मेनू दोहराने के लिए 0 दबाएं।"
    },
    spokenResponses: {
      findJobs: "उपलब्ध नौकरियां खुल रही हैं।",
      myWorks: "आपके सक्रिय कार्यों की सूची खुल रही है।",
      attendance: "हाजिरी ट्रैकर खुल रहा है।",
      wages: "आपकी मजदूरी का रिकॉर्ड दिखाया जा रहा है।",
      insurance: "बीमा डैशबोर्ड खुल रहा है।",
      feedback: "फीडबैक फॉर्म खुल रहा है।",
      support: "एआई चैट सहायता खुल रही है।",
      rentals: "किराया बाजार खुल रहा है।",
      overview: "एडमिन सिस्टम स्टेटस डैशबोर्ड खुल गया है। वर्तमान में 2 पंजीकृत उपयोगकर्ता, 1 सक्रिय नौकरी, और फायरस्टोर सर्वर कनेक्टेड है।",
      languageChanged: "भाषा बदलकर हिन्दी कर दी गई है।",
      notUnderstood: "मुझे समझ नहीं आया। कृपया एक मेनू नंबर बोलें या दोहराएं बोलें।",
      repeatMenu: "मेन्यू विकल्प दोहराया जा रहा है।"
    }
  },
  kn: {
    title: "ಎಐ ಐವಿಆರ್ ಸಹಾಯಕ",
    assistantReady: "ಸಹಾಯಕ ಸಿದ್ಧರಿದ್ದಾರೆ",
    sayCommand: "ಕಮಾಂಡ್ ಅಥವಾ ಸಂಖ್ಯೆಯನ್ನು ಹೇಳಿ",
    selectSpokenLanguage: "ಮಾತನಾಡುವ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    repeat: "ಪುನರಾವರ್ತಿಸಿ (0)",
    stopTTS: "ಧ್ವನಿ ನಿಲ್ಲಿಸಿ",
    close: "ಮುಚ್ಚಿ",
    listening: "ಕೇಳಿಸಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ... ಈಗ ಮಾತನಾಡಿ",
    speaking: "ಸೂಚನೆಗಳನ್ನು ಹೇಳಲಾಗುತ್ತಿದೆ...",
    openingPage: "ವಿನಂತಿಸಿದ ಪುಟವನ್ನು ತೆರೆಯಲಾಗುತ್ತಿದೆ...",
    easyMode: "ಸುಲಭ ಮೋಡ್",
    trySaying: "ಹೇಳಲು ಪ್ರಯತ್ನಿಸಿ / ಹೊಂದಿಸಿ",
    userInputLabel: "ಬಳಕೆದಾರರು ಹೇಳಿದ್ದು",
    detectedIntentLabel: "ಪತ್ತೆಯಾಗಿದೆ",
    aiResponseLabel: "ಎಐ ಪ್ರತಿಕ್ರಿಯೆ",
    actionStatusLabel: "ಕ್ರಮ",
    navigatingStatus: "ನ್ಯಾವಿಗೇಟ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    waitingStatus: "ಕಾಯಲಾಗುತ್ತಿದೆ...",
    confirmQuestion: "ನೀವು ಮುಂದುವರಿಸಲು ಬಯಸುವಿರಾ? ಹೌದು ಅಥವಾ ಇಲ್ಲ ಎಂದು ಹೇಳಿ.",
    confidenceLow: "ನಾನು ಕೇಳಿದೆ ಆದರೆ ನನಗೆ ಖಚಿತವಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೊಮ್ಮೆ ಹೇಳಿ.",
    helpText: "ನೀವು ಕೆಲಸ, ಸಂಬಳ, ಹಾಜರಾತಿ, ವಿಮೆ, ಬೆಂಬಲ ಅಥವಾ ಮೆನು ಸಂಖ್ಯೆಯನ್ನು ಹೇಳಬಹುದು.",
    notUnderstood: "ನನಗೆ ಅರ್ಥವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮೆನು ಸಂಖ್ಯೆಯನ್ನು ಹೇಳಿ ಅಥವಾ ಪುನರಾವರ್ತಿಸಿ ಎಂದು ಹೇಳಿ.",
    
    findJobs: "ಕೆಲಸ ಹುಡುಕಿ",
    myWorks: "ನನ್ನ ಕೆಲಸಗಳು",
    attendanceTracking: "ಹಾಜರಾತಿ ಟ್ರ್ಯಾಕಿಂಗ್",
    wagesManagement: "ವೇತನ ಟ್ರ್ಯಾಕಿಂಗ್",
    healthInsurance: "ಆರೋಗ್ಯ ವಿಮೆ",
    feedbackRating: "ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ರೇಟಿಂಗ್",
    chatSupport: "ಎಐ ಚಾಟ್ ಬೆಂಬಲ",
    hireLabour: "ಕಾರ್ಮಿಕರನ್ನು ನೇಮಿಸಿ",
    manageJobs: "ಕೆಲಸಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    rentalMarketplace: "ಬಾಡಿಗೆ ಮಾರುಕಟ್ಟೆ",
    attendanceManagement: "ಹಾಜರಾತಿ ನಿರ್ವಹಣೆ",
    wagesManagementOwner: "ವೇತನ ನಿರ್ವಹಣೆ",
    overview: "ಅವಲೋಕನ",
    userManagement: "ಬಳಕೆದಾರರ ನಿರ್ವಹಣೆ",
    activeJobs: "ಸಕ್ರಿಯ ಕೆಲಸಗಳು",
    rentalSystem: "ಬಾಡಿಗೆ ವ್ಯವಸ್ಥೆ",
    globalAttendance: "ಜಾಗತಿಕ ಹಾಜರಾತಿ",
    globalWages: "ಜಾಗತಿಕ ವೇತನ",
    profitsLedger: "ಲಾಭ ಮತ್ತು ಲೆಡ್ಜರ್",
    
    welcomeGreetings: {
      labour: "ಶ್ರಮಸೇತು ಕಾರ್ಮಿಕ ಪೋರ್ಟಲ್‌ಗೆ ಸುಸ್ವಾಗತ. ಕೆಲಸಗಳಿಗಾಗಿ 1 ಒತ್ತಿ ಅಥವಾ ಹೇಳಿ. ನನ್ನ ಕೆಲಸಗಳಿಗಾಗಿ 2. ಹಾಜರಾತಿಗಾಗಿ 3. ವೇತನಕ್ಕಾಗಿ 4. ವಿಮೆಗಾಗಿ 5. ಪ್ರತಿಕ್ರಿಯೆಗಾಗಿ 6. ಎಐ ಬೆಂಬಲಕ್ಕಾಗಿ 7. ಅಥವಾ ಮೆನುವನ್ನು ಪುನರಾವರ್ತಿಸಲು 0 ಒತ್ತಿ.",
      owner: "ಶ್ರಮಸೇತು ಮಾಲೀಕರ ಪೋರ್ಟಲ್‌ಗೆ ಸುಸ್ವಾಗತ. ಕಾರ್ಮಿಕರನ್ನು ನೇಮಿಸಲು 1 ಒತ್ತಿ ಅಥವಾ ಹೇಳಿ. ಕೆಲಸಗಳನ್ನು ನಿರ್ವಹಿಸಲು 2. ಬಾಡಿಗೆ ಮಾರುಕಟ್ಟೆಗಾಗಿ 3. ಹಾಜರಾತಿಗಾಗಿ 4. ವೇತನಕ್ಕಾಗಿ 5. ವಿಮೆಗಾಗಿ 6. ಪ್ರತಿಕ್ರಿಯೆಗಾಗಿ 7. ಚಾಟ್ ಬೆಂಬಲಕ್ಕಾಗಿ 8. ಅಥವಾ ಮೆನುವನ್ನು ಪುನರಾವರ್ತಿಸಲು 0 ಒತ್ತಿ.",
      admin: "ಶ್ರಮಸೇತು ನಿರ್ವಾಹಕರ ಪೋರ್ಟಲ್‌ಗೆ ಸುಸ್ವಾಗತ. ಅವಲೋಕನಕ್ಕಾಗಿ 1 ಒತ್ತಿ ಅಥವಾ ಹೇಳಿ. ಬಳಕೆದಾರರ ನಿರ್ವಹಣೆಗಾಗಿ 2. ಸಕ್ರಿಯ ಕೆಲಸಗಳಿಗಾಗಿ 3. ಬಾಡಿಗೆಗಾಗಿ 4. ಹಾಜರಾತಿಗಾಗಿ 5. ವೇತನಕ್ಕಾಗಿ 6. ವಿಮೆಗಾಗಿ 7. ಲಾಭಕ್ಕಾಗಿ 8. ಪ್ರತಿಕ್ರಿಯೆಗಾಗಿ 9. ಬೆಂಬಲಕ್ಕಾಗಿ 10. ಅಥವಾ ಮೆನುವನ್ನು ಪುನರಾವರ್ತಿಸಲು 0 ಒತ್ತಿ."
    },
    spokenResponses: {
      findJobs: "ಲಭ್ಯವಿರುವ ಕೆಲಸಗಳು ತೆರೆಯುತ್ತಿವೆ.",
      myWorks: "ನಿಮ್ಮ ಸಕ್ರಿಯ ಕೆಲಸಗಳ ಪಟ್ಟಿ ತೆರೆಯುತ್ತಿದೆ.",
      attendance: "ಹಾಜರಾತಿ ಟ್ರ್ಯಾಕರ್ ತೆರೆಯುತ್ತಿದೆ.",
      wages: "ನಿಮ್ಮ ವೇತನ ದಾಖಲೆಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ.",
      insurance: "ವಿಮಾ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ತೆರೆಯುತ್ತಿದೆ.",
      feedback: "ಪ್ರತಿಕ್ರಿಯೆ ಫಾರ್ಮ್ ತೆರೆಯುತ್ತಿದೆ.",
      support: "ಎಐ ಚಾಟ್ ಬೆಂಬಲ ತೆರೆಯುತ್ತಿದೆ.",
      rentals: "ಬಾಡಿಗೆ ಮಾರುಕಟ್ಟೆ ತೆರೆಯುತ್ತಿದೆ.",
      overview: "ನಿರ್ವಾಹಕ ವ್ಯವಸ್ಥೆಯ ಸ್ಥಿತಿಗತಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ತೆರೆಯಲಾಗಿದೆ. ಪ್ರಸ್ತುತ 2 ನೋಂದಾಯಿತ ಬಳಕೆದಾರರು, 1 ಸಕ್ರಿಯ ಕೆಲಸ, ಮತ್ತು ಫೈರ್‌ಸ್ಟೋರ್ ಸರ್ವರ್ ಸಂಪರ್ಕಗೊಂಡಿದೆ.",
      languageChanged: "ಭಾಷೆಯನ್ನು ಕನ್ನಡಕ್ಕೆ ಬದಲಾಯಿಸಲಾಗಿದೆ.",
      notUnderstood: "ನನಗೆ ಅರ್ಥವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮೆನು ಸಂಖ್ಯೆಯನ್ನು ಹೇಳಿ ಅಥವಾ ಪುನರಾವರ್ತಿಸಿ ಎಂದು ಹೇಳಿ.",
      repeatMenu: "ಮೆನು ಆಯ್ಕೆಗಳನ್ನು ಪುನರಾವರ್ತಿಸಲಾಗುತ್ತಿದೆ."
    }
  },
  ta: {
    title: "AI IVR உதவியாளர்",
    assistantReady: "உதவியாளர் தயார்",
    sayCommand: "கட்டளை அல்லது எண்ணைச் சொல்லவும்",
    selectSpokenLanguage: "பேசும் மொழியைத் தேர்ந்தெடுக்கவும்",
    repeat: "மீண்டும் செய் (0)",
    stopTTS: "குரலை நிறுத்து",
    close: "மூடு",
    listening: "கேட்கிறது... இப்போது பேசவும்",
    speaking: "அறிவுறுத்தல்களைப் பேசுகிறது...",
    openingPage: "கோரப்பட்ட பக்கத்தைத் திறக்கிறது...",
    easyMode: "எளிதான முறை",
    trySaying: "சொல்ல முயற்சிக்கவும் / பொருத்தவும்",
    userInputLabel: "பயனர் கூறியது",
    detectedIntentLabel: "கண்டறியப்பட்டது",
    aiResponseLabel: "AI பதில்",
    actionStatusLabel: "செயல்",
    navigatingStatus: "செல்கிறது...",
    waitingStatus: "காத்திருக்கிறது...",
    confirmQuestion: "தொடர விரும்புகிறீர்களா? ஆம் அல்லது இல்லை என்று சொல்லுங்கள்.",
    confidenceLow: "நான் கேட்டேன், ஆனால் எனக்கு உறுதியாக தெரியவில்லை. தயவுசெய்து மீண்டும் சொல்லுங்கள்.",
    helpText: "நீங்கள் வேலை, சம்பளம், வருகை, காப்பீடு, உதவி அல்லது மெனு எண்ணைச் சொல்லலாம்.",
    notUnderstood: "எனக்குப் புரியவில்லை. தயவுசெய்து மெனு எண்ணைச் சொல்லவும் அல்லது மீண்டும் சொல்லவும்.",
    
    findJobs: "வேலை தேடு",
    myWorks: "எனது வேலைகள்",
    attendanceTracking: "வருகை கண்காணிப்பு",
    wagesManagement: "கூலி கண்காணிப்பு",
    healthInsurance: "ஆரோக்கிய காப்பீடு",
    feedbackRating: "கருத்து மற்றும் மதிப்பீடு",
    chatSupport: "AI சாட் உதவி",
    hireLabour: "கார்மிக் வாடகைக்கு",
    manageJobs: "வேலைகளை நிர்வகி",
    rentalMarketplace: "வாடகை சந்தை",
    attendanceManagement: "வருகை மேலாண்மை",
    wagesManagementOwner: "கூலி மேலாண்மை",
    overview: "கண்ணோட்டம்",
    userManagement: "பயனர் மேலாண்மை",
    activeJobs: "செயலில் உள்ள வேலைகள்",
    rentalSystem: "வாடகை அமைப்பு",
    globalAttendance: "உலகளாவிய வருகை",
    globalWages: "உலகளாவிய கூலி",
    profitsLedger: "லாபம் மற்றும் லெட்ஜர்",
    
    welcomeGreetings: {
      labour: "ஷ்ரமஸேது தொழிலாளர் போர்ட்டலுக்கு உங்களை வரவேற்கிறோம். வேலைகளுக்கு 1 ஐ அழுத்தவும் அல்லது சொல்லவும். எனது வேலைகளுக்கு 2. வருகைக்கு 3. கூலிக்கு 4. காப்பீட்டுக்கு 5. கருத்துக்கு 6. AI உதவிக்கு 7. அல்லது மெனுவை மீண்டும் செய்ய 0 ஐ அழுத்தவும்.",
      owner: "ஷ்ரமஸேது முதலாளி போர்ட்டலுக்கு உங்களை வரவேற்கிறோம். தொழிலாளர்களை நியமிக்க 1 ஐ அழுத்தவும் அல்லது சொல்லவும். வேலைகளை நிர்வகிக்க 2. வாடகை சந்தைக்கு 3. வருகைக்கு 4. கூலிக்கு 5. காப்பீட்டுக்கு 6. கருத்துக்கு 7. சாட் உதவிக்கு 8. அல்லது மெனுவை மீண்டும் செய்ய 0 ஐ அழுத்தவும்.",
      admin: "ஷ்ரமஸேது நிர்வாகி போர்ட்டலுக்கு உங்களை வரவேற்கிறோம். கண்ணோட்டத்திற்கு 1 ஐ அழுத்தவும் அல்லது சொல்லவும். பயனர் மேலாண்மைக்கு 2. செயலில் உள்ள வேலைகளுக்கு 3. வாடகைக்கு 4. வருகைக்கு 5. கூலிக்கு 6. காப்பீட்டுக்கு 7. லாபத்திற்கு 8. கருத்துக்கு 9. உதவிக்கு 10. அல்லது மெனுவை மீண்டும் செய்ய 0 ஐ அழுத்தவும்."
    },
    spokenResponses: {
      findJobs: "கிடைக்கும் வேலைகள் திறக்கப்படுகின்றன.",
      myWorks: "உங்கள் செயலில் உள்ள வேலைகளின் பட்டியல் திறக்கப்படுக்கிறது.",
      attendance: "வருகை டிராக்கர் திறக்கப்படுகிறது.",
      wages: "உங்கள் கூலி பதிவுகள் காண்பிக்கப்படுகின்றன.",
      insurance: "காப்பீட்டு டாஷ்போர்டு திறக்கப்படுகிறது.",
      feedback: "கருத்து படிவம் திறக்கப்படுகிறது.",
      support: "AI சாட் உதவி திறக்கப்படுகிறது.",
      rentals: "வாடகை சந்தை திறக்கப்படுகிறது.",
      overview: "நிர்வாகி கணினி நிலை டாஷ்போர்டு திறக்கப்பட்டுள்ளது. தற்போது 2 பதிவு செய்யப்பட்ட பயனர்கள், 1 செயலில் உள்ள வேலை மற்றும் ஃபயர்ஸ்டோர் சர்வர் இணைக்கப்பட்டுள்ளது.",
      languageChanged: "மொழி தமிழுக்கு மாற்றப்பட்டுள்ளது.",
      notUnderstood: "எனக்குப் புரியவில்லை. தயவுசெய்து மெனு எண்ணைச் சொல்லவும் அல்லது மீண்டும் சொல்லவும்.",
      repeatMenu: "மெனு விருப்பங்கள் மீண்டும் செய்யப்படுகின்றன."
    }
  },
  te: {
    title: "AI IVR సహాయకుడు",
    assistantReady: "సహాయకుడు సిద్ధంగా ఉన్నాడు",
    sayCommand: "ఆదేశం లేదా సంఖ్యను చెప్పండి",
    selectSpokenLanguage: "మాట్లాడే భాషను ఎంచుకోండి",
    repeat: "పునరావృతం (0)",
    stopTTS: "వాయిస్ ఆపు",
    close: "మూసివేయి",
    listening: "వింటోంది... ఇప్పుడు మాట్లాడండి",
    speaking: "సూచనలు చెబుతోంది...",
    openingPage: "కోరిన పేజీ తెరవబడుతోంది...",
    easyMode: "సులభమైన మోడ్",
    trySaying: "చెప్పడానికి ప్రయత్నించండి / సరిపోల్చండి",
    userInputLabel: "వినియోగదారు చెప్పారు",
    detectedIntentLabel: "గుర్తించబడింది",
    aiResponseLabel: "AI ప్రతిస్పందన",
    actionStatusLabel: "చర్య",
    navigatingStatus: "నావిగేట్ అవుతోంది...",
    waitingStatus: "వేచి ఉంది...",
    confirmQuestion: "మీరు కొనసాగించాలనుకుంటున్నారా? అవును లేదా కాదు అని చెప్పండి.",
    confidenceLow: "నేను విన్నాను కానీ నాకు ఖచ్చితంగా తెలియదు. దయచేసి ఒకసారి మళ్లీ చెప్పండి.",
    helpText: "మీరు ఉద్యోగం, జీతం, హాజరు, భీమా, మద్దతు లేదా మెను నంబర్‌ను చెప్పవచ్చు.",
    notUnderstood: "నాకు అర్థం కాలేదు. దయచేసి మెను నంబర్ చెప్పండి లేదా పునరావృతం చేయండి.",
    
    findJobs: "ఉద్యోగం వెతకండి",
    myWorks: "నా పనులు",
    attendanceTracking: "హాజరు ట్రాకింగ్",
    wagesManagement: "వేతన ట్రాకింగ్",
    healthInsurance: "ఆరోగ్య భీమా",
    feedbackRating: "అభిప్రాయం & రేటింగ్",
    chatSupport: "AI చాట్ సపోర్ట్",
    hireLabour: "కార్మికులను నియమించండి",
    manageJobs: "ఉద్యోగాలు నిర్వహించండి",
    rentalMarketplace: "అద్దె మార్కెట్",
    attendanceManagement: "హాజరు నిర్వహణ",
    wagesManagementOwner: "వేతన నిర్వహణ",
    overview: "అవలోకనం",
    userManagement: "వినియోగదారుల నిర్వహణ",
    activeJobs: "సక్రియ ఉద్యోగాలు",
    rentalSystem: "అద్దె వ్యవస్థ",
    globalAttendance: "గ్లోబల్ హాజరు",
    globalWages: "గ్లోబల్ వేతనాలు",
    profitsLedger: "లాభాలు & లెడ్జర్",
    
    welcomeGreetings: {
      labour: "శ్రమసేతు కార్మిక పోర్టల్‌కు స్వాగతం. ఉద్యోగాల కోసం 1 నొక్కండి లేదా చెప్పండి. నా పనుల కోసం 2. హాజరు కోసం 3. వేతనాల కోసం 4. భీమా కోసం 5. అభిప్రాయం కోసం 6. AI సపోర్ట్ కోసం 7. లేదా మెనూని పునరావృతం చేయడానికి 0 నొక్కండి.",
      owner: "శ్రమసేతు యజమాని పోర్టల్‌కు స్వాగతం. కార్మికులను నియమించడానికి 1 నొక్కండి లేదా చెప్పండి. ఉద్యోగాలను నిర్వహించడానికి 2. అద్దె మార్కెట్ కోసం 3. హాజరు కోసం 4. వేతనాల కోసం 5. భీమా కోసం 6. అభిప్రాయం కోసం 7. చాట్ సపోర్ట్ కోసం 8. లేదా మెనూని పునరావృతం చేయడానికి 0 నొక్కండి.",
      admin: "శ్రమసేతు అడ్మిన్ పోర్టల్‌కు స్వాగతం. అవలోకనం కోసం 1 నొక్కండి లేదా చెప్పండి. వినియోగదారుల నిర్వహణ కోసం 2. సక్రియ ఉద్యోగాల కోసం 3. అద్దె కోసం 4. హాజరు కోసం 5. వేతనాల కోసం 6. భీమా కోసం 7. లాభాల కోసం 8. అభిప్రాయం కోసం 9. సపోర్ట్ కోసం 10. లేదా మెనూని పునరావృతం చేయడానికి 0 నొక్కండి."
    },
    spokenResponses: {
      findJobs: "అందుబాటులో ఉన్న ఉద్యోగాలు తెరవబడుతున్నాయి.",
      myWorks: "మీ సక్రియ పనుల జాబితా తెరవబడుతోంది.",
      attendance: "హాజరు ట్రాకర్ తెరవబడుతోంది.",
      wages: "మీ వేతన రికార్డులు చూపబడుతున్నాయి.",
      insurance: "భీమా డాష్‌బోర్డ్ తెరవబడుతోంది.",
      feedback: "అభిప్రాయ ఫారమ్ తెరవబడుతోంది.",
      support: "AI చాట్ సపోర్ట్ తెరవబడుతోంది.",
      rentals: "అద్దె మార్కెట్ తెరవబడుతోంది.",
      overview: "నిర్వాహక వ్యవస్థ స్థితి డాష్‌బోర్డ్ తెరవబడింది. ప్రస్తుతం 2 నమోదిత వినియోగదారులు, 1 సక్రియ ఉద్యోగం మరియు ఫైర్‌స్టోర్ సర్వర్ కనెక్ట్ చేయబడింది.",
      languageChanged: "భాష తెలుగులోకి మార్చబడింది.",
      notUnderstood: "నాకు అర్థం కాలేదు. దయచేసి మెను నంబర్ చెప్పండి లేదా పునరావృతం చేయండి.",
      repeatMenu: "మెనూ ఎంపికలు పునరావృతం అవుతున్నాయి."
    }
  },
  ml: {
    title: "AI IVR അസിസ്റ്റന്റ്",
    assistantReady: "അസിസ്റ്റന്റ് തയ്യാറാണ്",
    sayCommand: "ഒരു കമാൻഡ് അല്ലെങ്കിൽ നമ്പർ പറയുക",
    selectSpokenLanguage: "സംസാരിക്കുന്ന ഭാഷ തിരഞ്ഞെടുക്കുക",
    repeat: "ആവർത്തിക്കുക (0)",
    stopTTS: "വോയ്‌സ് നിർത്തുക",
    close: "അടയ്ക്കുക",
    listening: "ശ്രദ്ധിക്കുന്നു... ഇപ്പോൾ സംസാരിക്കുക",
    speaking: "നിർദ്ദേശങ്ങൾ സംസാരിക്കുന്നു...",
    openingPage: "ആവശ്യപ്പെട്ട പേജ് തുറക്കുന്നു...",
    easyMode: "ലളിതമായ മോഡ്",
    trySaying: "പറയാൻ ശ്രമിക്കുക / പൊരുത്തപ്പെടുത്തുക",
    userInputLabel: "ഉപയോക്താവ് പറഞ്ഞത്",
    detectedIntentLabel: "കണ്ടെത്തി",
    aiResponseLabel: "AI മറുപടി",
    actionStatusLabel: "പ്രവർത്തനം",
    navigatingStatus: "നാവിഗേറ്റ് ചെയ്യുന്നു...",
    waitingStatus: "കാത്തിരിക്കുന്നു...",
    confirmQuestion: "നിങ്ങൾക്ക് തുടരണമെന്നുണ്ടോ? അതെ അല്ലെങ്കിൽ ഇല്ല എന്ന് പറയുക.",
    confidenceLow: "ഞാൻ കേട്ടു പക്ഷെ എനിക്ക് ഉറപ്പില്ല. ദയവായി ഒരിക്കൽ കൂടി പറയുക.",
    helpText: "നിങ്ങൾക്ക് ജോലി, ശമ്പളം, ഹാജർ, ഇൻഷുറൻസ്, പിന്തുണ അല്ലെങ്കിൽ ഒരു മെനു നമ്പർ പറയാം.",
    notUnderstood: "എനിക്ക് മനസ്സിലായില്ല. ദയവായി ഒരു മെനു നമ്പർ പറയുക അല്ലെങ്കിൽ ആവർത്തിക്കുക എന്ന് പറയുക.",
    
    findJobs: "ജോലി കണ്ടെത്തുക",
    myWorks: "എന്റെ ജോലികൾ",
    attendanceTracking: "ഹാജർ ട്രാക്കിംഗ്",
    wagesManagement: "കൂലി ട്രാക്കിംഗ്",
    healthInsurance: "ആരോഗ്യ ഇൻഷുറൻസ്",
    feedbackRating: "അഭിപ്രായവും റേറ്റിംഗും",
    chatSupport: "AI ചാറ്റ് പിന്തുണ",
    hireLabour: "തൊഴിലാളികളെ നിയമിക്കുക",
    manageJobs: "ജോലികൾ നിയന്ത്രിക്കുക",
    rentalMarketplace: "വാടക വിപണി",
    attendanceManagement: "ഹാജർ മാനേജ്‌മെന്റ്",
    wagesManagementOwner: "കൂലി മാനേജ്‌മെന്റ്",
    overview: "അവലോകനം",
    userManagement: "ഉപയോക്തൃ മാനേജ്‌മെന്റ്",
    activeJobs: "സജീവ ജോലികൾ",
    rentalSystem: "വാടക സംവിധാനം",
    globalAttendance: "ആഗോള ഹാജർ",
    globalWages: "ആഗോള കൂലി",
    profitsLedger: "ലാഭവും ലെഡ്ജറും",
    
    welcomeGreetings: {
      labour: "ശ്രമസേതു തൊഴിലാളി പോർട്ടലിലേക്ക് സ്വാഗതം. ജോലികൾക്കായി 1 അമർത്തുക അല്ലെങ്കിൽ പറയുക. എന്റെ ജോലികൾക്കായി 2. ഹാജരിനായി 3. കൂലിക്കായി 4. ഇൻഷുറൻസിനായി 5. അഭിപ്രായത്തിനായി 6. AI പിന്തുണയ്ക്കായി 7. അല്ലെങ്കിൽ മെനു ആവർത്തിക്കാൻ 0 അമർത്തുക.",
      owner: "ശ്രമസേതു ഉടമസ്ഥ പോർട്ടലിലേക്ക് സ്വാഗതം. തൊഴിലാളികളെ നിയമിക്കാൻ 1 അമർത്തുക അല്ലെങ്കിൽ പറയുക. ജോലികൾ നിയന്ത്രിക്കാൻ 2. വാടക വിപണിക്കായി 3. ഹാജരിനായി 4. കൂലിക്കായി 5. ഇൻഷുറൻസിനായി 6. അഭിപ്രായത്തിനായി 7. ചാറ്റ് പിന്തുണയ്ക്കായി 8. അല്ലെങ്കിൽ മെനു ആവർത്തിക്കാൻ 0 അമർത്തുക.",
      admin: "ശ്രമസേതു അഡ്മിൻ പോർട്ടലിലേക്ക് സ്വാഗതം. അവലോകനത്തിനായി 1 അമർത്തുക അല്ലെങ്കിൽ പറയുക. ഉപയോക്തൃ മാനേജ്‌മെന്റിനായി 2. സജീവ ജോലികൾക്കായി 3. വാടകയ്ക്കായി 4. ഹാജരിനായി 5. കൂലിക്കായി 6. ഇൻഷുറൻസിനായി 7. ലാഭത്തിനായി 8. അഭിപ്രായത്തിനായി 9. പിന്തുണയ്ക്കായി 10. അല്ലെങ്കിൽ മെനു ആവർത്തിക്കാൻ 0 അമർത്തുക."
    },
    spokenResponses: {
      findJobs: "ലഭ്യമായ ജോലികൾ തുറക്കുന്നു.",
      myWorks: "നിങ്ങളുടെ സജീവ ജോലികളുടെ പട്ടിക തുറക്കുന്നു.",
      attendance: "ഹാജർ ട്രാക്കർ തുറക്കുന്നു.",
      wages: "നിങ്ങളുടെ കൂലി രേഖകൾ കാണിക്കുന്നു.",
      insurance: "ഇൻഷുറൻസ് ഡാഷ്‌ബോർഡ് തുറക്കുന്നു.",
      feedback: "അഭിപ്രായ ഫോം തുറക്കുന്നു.",
      support: "AI ചാറ്റ് പിന്തുണ തുറക്കുന്നു.",
      rentals: "വാടക വിപണി തുറക്കുന്നു.",
      overview: "അഡ്മിൻ സിസ്റ്റം സ്റ്റാറ്റസ് ഡാഷ്‌ബോർഡ് തുറന്നു. നിലവിൽ 2 രജിസ്റ്റർ ചെയ്ത ഉപയോക്താക്കൾ, 1 സജീവ ജോലി, കൂടാതെ ഫയർസ്റ്റോർ സെർവർ കണക്റ്റുചെയ്‌തിരിക്കുന്നു.",
      languageChanged: "ഭാഷ മലയാളത്തിലേക്ക് മാറ്റിയിരിക്കുന്നു.",
      notUnderstood: "എനിക്ക് മനസ്സിലായില്ല. ദയവായി ഒരു മെനു നമ്പർ പറയുക അല്ലെങ്കിൽ ആവർത്തിക്കുക എന്ന് പറയുക.",
      repeatMenu: "മെനു ഓപ്ഷനുകൾ ആവർത്തിക്കുന്നു."
    }
  },
  mr: {
    title: "एआय आयवीआर सहाय्यक",
    assistantReady: "सहाय्यक तयार आहे",
    sayCommand: "कमांड किंवा संख्या बोला",
    selectSpokenLanguage: "बोलण्याची भाषा निवडा",
    repeat: "पुन्हा सांगा (0)",
    stopTTS: "आवाज थांबवा",
    close: "बंद करा",
    listening: "ऐकत आहे... आता बोला",
    speaking: "सूचना सांगत आहे...",
    openingPage: "विनंती केलेले पृष्ठ उघडत आहे...",
    easyMode: "सुलभ मोड",
    trySaying: "बोलण्याचा प्रयत्न करा / जुळवा",
    userInputLabel: "वापरकर्त्याने सांगितले",
    detectedIntentLabel: "आढळले",
    aiResponseLabel: "AI प्रतिसाद",
    actionStatusLabel: "कृती",
    navigatingStatus: "नेव्हिगेट करत आहे...",
    waitingStatus: "प्रतीक्षा करत आहे...",
    confirmQuestion: "तुम्हाला पुढे जायचे आहे का? होय किंवा नाही सांगा.",
    confidenceLow: "मी ऐकले पण मला खात्री नाही. कृपया एकदा पुन्हा सांगा.",
    helpText: "तुम्ही नोकरी, मजुरी, हजेरी, विमा, मदत किंवा मेनू क्रमांक सांगू शकता.",
    notUnderstood: "मला समजले नाही. कृपया मेनू क्रमांक सांगा किंवा पुन्हा सांगा.",
    
    findJobs: "काम शोधा",
    myWorks: "माझी कामे",
    attendanceTracking: "हजेरी ट्रॅकिंग",
    wagesManagement: "मजुरी ट्रॅकिंग",
    healthInsurance: "आरोग्य विमा",
    feedbackRating: "अभिप्राय आणि रेटिंग",
    chatSupport: "एआय चॅट मदत",
    hireLabour: "मजूर नियुक्त करा",
    manageJobs: "कामे व्यवस्थापित करा",
    rentalMarketplace: "भाडे बाजारपेठ",
    attendanceManagement: "हजेरी व्यवस्थापन",
    wagesManagementOwner: "मजुरी व्यवस्थापन",
    overview: "आढावा",
    userManagement: "वापरकर्ता व्यवस्थापन",
    activeJobs: "सक्रिय कामे",
    rentalSystem: "भाडे प्रणाली",
    globalAttendance: "जागतिक हजेरी",
    globalWages: "जागतिक मजुरी",
    profitsLedger: "नफा आणि खातेवही",
    
    welcomeGreetings: {
      labour: "श्रमसेतू कामगार पोर्टलवर आपले स्वागत आहे. काम शोधण्यासाठी 1 दाबा किंवा बोला. माझ्या कामासाठी 2. हजेरीसाठी 3. मजुरीसाठी 4. विम्यासाठी 5. अभिप्रायासाठी 6. एआय मदतीसाठी 7. किंवा मेनू पुन्हा सांगण्यासाठी 0 दाबा.",
      owner: "श्रमसेतू मालक पोर्टलवर आपले स्वागत आहे. मजूर नियुक्त करण्यासाठी 1 दाबा किंवा बोला. कामे व्यवस्थापित करण्यासाठी 2. भाडे बाजारपेठेसाठी 3. हजेरीसाठी 4. मजुरीसाठी 5. विम्यासाठी 6. अभिप्रायासाठी 7. चॅट मदतीसाठी 8. किंवा मेनू पुन्हा सांगण्यासाठी 0 दाबा.",
      admin: "श्रमसेतू ॲडमिन पोर्टलवर आपले स्वागत आहे. आढावा घेण्यासाठी 1 दाबा किंवा बोला. वापरकर्ता व्यवस्थापनासाठी 2. सक्रिय कामांसाठी 3. भाड्यासाठी 4. हजेरीसाठी 5. मजुरीसाठी 6. विम्यासाठी 7. नफ्यासाठी 8. अभिप्रायासाठी 9. मदतीसाठी 10. किंवा मेनू पुन्हा सांगण्यासाठी 0 दाबा."
    },
    spokenResponses: {
      findJobs: "उपलब्ध कामे उघडत आहेत.",
      myWorks: "तुमच्या सक्रिय कामांची यादी उघडत आहे.",
      attendance: "हजेरी ट्रॅकर उघडत आहे.",
      wages: "तुमचे मजुरीचे रेकॉर्ड दाखवले जात आहेत.",
      insurance: "विमा डॅशबोर्ड उघडत आहे.",
      feedback: "अभिप्राय फॉर्म उघडत आहे.",
      support: "एआय चॅट मदत उघडत आहे.",
      rentals: "भाडे बाजारपेठ उघडत आहे.",
      overview: "ॲडमिन प्रणाली स्थिती डॅशबोर्ड उघडला आहे. सध्या 2 नोंदणीकृत वापरकर्ते, 1 सक्रिय काम आणि फायरस्टोर सर्व्हर जोडलेला आहे.",
      languageChanged: "भाषा मराठीत बदलली आहे.",
      notUnderstood: "मला समजले नाही. कृपया मेनू क्रमांक सांगा किंवा पुन्हा सांगा.",
      repeatMenu: "मेन्यू पर्याय पुन्हा सांगितले जात आहेत."
    }
  },
  bn: {
    title: "এআই আইভিআর সহকারী",
    assistantReady: "সহকারী প্রস্তুত",
    sayCommand: "একটি কমান্ড বা সংখ্যা বলুন",
    selectSpokenLanguage: "কথ্য ভাষা নির্বাচন করুন",
    repeat: "পুনরাবৃত্তি (0)",
    stopTTS: "ভয়েস বন্ধ করুন",
    close: "বন্ধ করুন",
    listening: "শুনছি... এখন বলুন",
    speaking: "নির্দেশাবলী বলা হচ্ছে...",
    openingPage: "অনুরোধ করা পৃষ্ঠা খোলা হচ্ছে...",
    easyMode: "সহজ মোড",
    trySaying: "বলার চেষ্টা করুন / মেলান",
    userInputLabel: "ব্যবহারকারী বলেছেন",
    detectedIntentLabel: "শনাক্ত হয়েছে",
    aiResponseLabel: "AI প্রতিক্রিয়া",
    actionStatusLabel: "পদক্ষেপ",
    navigatingStatus: "নেভিগেট করা হচ্ছে...",
    waitingStatus: "অপেক্ষা করা হচ্ছে...",
    confirmQuestion: "আপনি কি চালিয়ে যেতে চান? হ্যাঁ বা না বলুন।",
    confidenceLow: "আমি শুনেছি তবে আমি নিশ্চিত নই। অনুগ্রহ করে আবার বলুন।",
    helpText: "আপনি চাকরি, মজুরি, হাজিরা, বীমা, সহায়তা বা একটি মেনু নম্বর বলতে পারেন।",
    notUnderstood: "আমি বুঝতে পারিনি। অনুগ্রহ করে একটি মেনু নম্বর বলুন বা পুনরাবৃত্তি বলুন।",
    
    findJobs: "কাজ খুঁজুন",
    myWorks: "আমার কাজ",
    attendanceTracking: "হাজিরা ট্র্যাকিং",
    wagesManagement: "মজুরি ট্র্যাকিং",
    healthInsurance: "স্বাস্থ্য বীমা",
    feedbackRating: "মতামত ও রেটিং",
    chatSupport: "এআই চ্যাট সাপোর্ট",
    hireLabour: "শ্রমিক নিয়োগ করুন",
    manageJobs: "কাজ পরিচালনা করুন",
    rentalMarketplace: "ভাড়া বাজার",
    attendanceManagement: "হাজিরা পরিচালনা",
    wagesManagementOwner: "মজুরি পরিচালনা",
    overview: "পর্যালোচনা",
    userManagement: "ব্যবহারকারী পরিচালনা",
    activeJobs: "সক্রিয় কাজ",
    rentalSystem: "ভাড়া ব্যবস্থা",
    globalAttendance: "বৈশ্বিক হাজিরা",
    globalWages: "বৈশ্বিক মজুরি",
    profitsLedger: "লাভ এবং খতিয়ান",
    
    welcomeGreetings: {
      labour: "শ্রমসেতু শ্রমিক পোর্টালে আপনাকে স্বাগত জানাই। কাজ খোঁজার জন্য 1 টিপুন বা বলুন। আমার কাজের জন্য 2। হাজিরার জন্য 3। মজুরির জন্য 4। বীমার জন্য 5। মতামতের জন্য 6। এআই সাপোর্টের জন্য 7। অথবা মেনু পুনরাবৃত্তি করতে 0 টিপুন।",
      owner: "শ্রমসেতু মালিক পোর্টালে আপনাকে স্বাগত জানাই। শ্রমিক নিয়োগের জন্য 1 টিপুন বা বলুন। কাজ পরিচালনার জন্য 2। ভাড়া বাজারের জন্য 3। হাজিরার জন্য 4। মজুরির জন্য 5। বীমার জন্য 6। মতামতের জন্য 7। চ্যাট সাপোর্টের জন্য 8। অথবা মেনু পুনরাবৃত্তি করতে 0 টিপুন।",
      admin: "শ্রমসেতু অ্যাডমিন পোর্টালে আপনাকে স্বাগত জানাই। পর্যালোচনার জন্য 1 টিপুন বা বলুন। ব্যবহারকারী পরিচালনার জন্য 2। সক্রিয় কাজের জন্য 3। ভাড়ার জন্য 4। হাজিরার জন্য 5। মজুরির জন্য 6। বীমার জন্য 7। লাভের জন্য 8। মতামতের জন্য 9। সাপোর্টের জন্য 10। অথবা মেনু পুনরাবৃত্তি করতে 0 টিপুন।"
    },
    spokenResponses: {
      findJobs: "উপলব্ধ কাজের সুযোগগুলি খোলা হচ্ছে।",
      myWorks: "আপনার সক্রিয় কাজের তালিকা খোলা হচ্ছে।",
      attendance: "হাজিরা ট্র্যাকার খোলা হচ্ছে।",
      wages: "আপনার মজুরির রেকর্ড দেখানো হচ্ছে।",
      insurance: "বীমা ড্যাশবোর্ড খোলা হচ্ছে।",
      feedback: "মতামত ফর্ম খোলা হচ্ছে।",
      support: "এআই চ্যাট সাপোর্ট খোলা হচ্ছে।",
      rentals: "ভাড়ার বাজার খোলা হচ্ছে।",
      overview: "অ্যাডমিন সিস্টেম স্ট্যাটাস ড্যাশবোর্ড খোলা হয়েছে। বর্তমানে 2 জন নিবন্ধিত ব্যবহারকারী, 1টি সক্রিয় কাজ এবং ফায়ারস্টোর সার্ভার সংযুক্ত রয়েছে।",
      languageChanged: "ভাষা পরিবর্তন করে বাংলা করা হয়েছে।",
      notUnderstood: "আমি বুঝতে পারিনি। অনুগ্রহ করে একটি মেনু নম্বর বলুন বা পুনরাবৃত্তি বলুন।",
      repeatMenu: "মেনু বিকল্পগুলি পুনরাবৃত্তি করা হচ্ছে।"
    }
  },
  gu: {
    title: "એઆઈ આઈવીઆર સહાયક",
    assistantReady: "સહાયક તૈયાર છે",
    sayCommand: "કમાન્ડ અથવા સંખ્યા બોલો",
    selectSpokenLanguage: "બોલાતી ભાષા પસંદ કરો",
    repeat: "પુનરાવર્તન (0)",
    stopTTS: "અવાજ બંધ કરો",
    close: "બંધ કરો",
    listening: "સાંભળી રહ્યું છે... હવે બોલો",
    speaking: "સૂચનાઓ બોલાઈ રહી છે...",
    openingPage: "વિનંતી કરેલ પૃષ્ઠ ખુલી રહ્યું છે...",
    easyMode: "સરળ મોડ",
    trySaying: "બોલવાનો પ્રયત્ન કરો / મેળવો",
    userInputLabel: "વપરાશકર્તાએ કહ્યું",
    detectedIntentLabel: "શોધાયેલ",
    aiResponseLabel: "AI પ્રતિસાદ",
    actionStatusLabel: "ક્રિયા",
    navigatingStatus: "નેવિગેટ કરી રહ્યું છે...",
    waitingStatus: "રાહ જોઈ રહ્યું છે...",
    confirmQuestion: "શું તમે ચાલુ રાખવા માંગો છો? હા અથવા ના બોલો.",
    confidenceLow: "મેં સાંભળ્યું પણ મને ખાતરી નથી. કૃપા કરીને એકવાર ફરી બોલો.",
    helpText: "તમે નોકરી, મજૂરી, હાજરી, વીમો, સપોર્ટ અથવા મેનુ નંબર કહી શકો છો.",
    notUnderstood: "મને સમજાયું નહીં. કૃપા કરીને મેનૂ નંબર બોલો અથવા પુનરાવર્તન બોલો.",
    
    findJobs: "કામ શોધો",
    myWorks: "મારું કામ",
    attendanceTracking: "હાજરી ટ્રેકિંગ",
    wagesManagement: "મજૂરી ટ્રેકિંગ",
    healthInsurance: "આરોગ્ય વીમો",
    feedbackRating: "પ્રતિસાદ અને રેટિંગ",
    chatSupport: "એઆઈ ચેટ સપોર્ટ",
    hireLabour: "શ્રમિક ભાડે લો",
    manageJobs: "કામ વ્યવસ્થિત કરો",
    rentalMarketplace: "ભાડા બજાર",
    attendanceManagement: "હાજરી સંચાલન",
    wagesManagementOwner: "મજૂરી સંચાલન",
    overview: "અવલોકન",
    userManagement: "વપરાશકર્તા સંચાલન",
    activeJobs: "સક્રિય કામો",
    rentalSystem: "ભાડા પ્રણાલી",
    globalAttendance: "વૈશ્વિક હાજરી",
    globalWages: "વૈશ્વિક મજૂરી",
    profitsLedger: "નફો અને લેજર",
    
    welcomeGreetings: {
      labour: "શ્રમસેતુ શ્રમિક પોર્ટલ પર આપનું સ્વાગત છે. કામ શોધવા માટે 1 દબાવો અથવા બોલો. મારા કામ માટે 2. હાજરી માટે 3. મજૂરી માટે 4. વીમા માટે 5. પ્રતિસાદ માટે 6. એઆઈ સપોર્ટ માટે 7. અથવા મેનૂ પુનરાવર્તિત કરવા 0 દબાવો.",
      owner: "શ્રમસેતુ માલિક પોર્ટલ પર આપનું સ્વાગત છે. શ્રમિક ભાડે લેવા માટે 1 દબાવો અથવા બોલો. કામ સંચાલન માટે 2. ભાડા બજાર માટે 3. હાજરી માટે 4. મજૂરી માટે 5. વીમા માટે 6. પ્રતિસાદ માટે 7. ચેટ સપોર્ટ માટે 8. અથવા મેનૂ પુનરાવર્તિત કરવા 0 દબાવો.",
      admin: "શ્રમસેતુ એડમિન પોર્ટલ પર આપનું સ્વાગત છે. અવલોકન માટે 1 દબાવો અથવા બોલો. વપરાશકર્તા સંચાલન માટે 2. સક્રિય કામો માટે 3. ભાડા માટે 4. હાજરી માટે 5. મજૂરી માટે 6. વીમા માટે 7. નફા માટે 8. પ્રતિસાદ માટે 9. સપોર્ટ માટે 10. અથવા મેનૂ પુનરાવર્તિત કરવા 0 દબાવો."
    },
    spokenResponses: {
      findJobs: "ઉપલબ્ધ કામો ખુલી રહ્યા છે.",
      myWorks: "તમારા સક્રિય કામોની યાદી ખુલી રહી છે.",
      attendance: "હાજરી ટ્રેકર ખુલી રહ્યું છે.",
      wages: "તમારા મજૂરીના રેકોર્ડ દર્શાવવામાં આવી રહ્યા છે.",
      insurance: "વીમા ડેશબોર્ડ ખુલી રહ્યું છે.",
      feedback: "પ્રતિસાદ ફોર્મ ખુલી રહ્યું છે.",
      support: "એઆઈ ચેટ સપોર્ટ ખુલી રહ્યો છે.",
      rentals: "ભાડા બજાર ખુલી રહ્યું છે.",
      overview: "એડમિન સિસ્ટમ સ્ટેટસ ડેશબોર્ડ ખુલી ગયું છે. હાલમાં 2 નોંધાયેલા વપરાશકર્તાઓ, 1 સક્રિય કામ અને ફાયરસ્ટોર સર્વર જોડાયેલ છે.",
      languageChanged: "ભાષા બદલીને ગુજરાતી કરવામાં આવી છે.",
      notUnderstood: "મને સમજાયું નહીં. કૃપા કરીને મેનૂ નંબર બોલો અથવા પુનરાવર્તન બોલો.",
      repeatMenu: "મેનૂ વિકલ્પો પુનરાવર્તિત થઈ રહ્યા છે."
    }
  },
  pa: {
    title: "ਏਆਈ ਆਈਵੀਆਰ ਸਹਾਇਕ",
    assistantReady: "ਸਹਾਇਕ ਤਿਆਰ ਹੈ",
    sayCommand: "ਕੋਈ ਕਮਾਂਡ ਜਾਂ ਨੰਬਰ ਬੋਲੋ",
    selectSpokenLanguage: "ਬੋਲੀ ਜਾਣ ਵਾਲੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    repeat: "ਦੁਹਰਾਓ (0)",
    stopTTS: "ਆਵਾਜ਼ ਬੰਦ ਕਰੋ",
    close: "ਬੰਦ ਕਰੋ",
    listening: "ਸੁਣ ਰਿਹਾ ਹੈ... ਹੁਣ ਬੋਲੋ",
    speaking: "ਨਿਰਦੇਸ਼ ਬੋਲ ਰਿਹਾ ਹੈ...",
    openingPage: "ਬੇਨਤੀ ਕੀਤਾ ਪੰਨਾ ਖੋਲ੍ਹ ਰਿਹਾ ਹੈ...",
    easyMode: "ਆਸਾਨ ਮੋਡ",
    trySaying: "ਬੋਲਣ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰੋ / ਮਿਲਾਓ",
    userInputLabel: "ਉਪਭੋਗਤਾ ਨੇ ਕਿਹਾ",
    detectedIntentLabel: "ਪਤਾ ਲੱਗਿਆ",
    aiResponseLabel: "AI ਜਵਾਬ",
    actionStatusLabel: "ਕਾਰਵਾਈ",
    navigatingStatus: "ਨੈਵੀਗੇਟ ਕਰ ਰਿਹਾ ਹੈ...",
    waitingStatus: "ਉਡੀਕ ਕਰ ਰਿਹਾ ਹੈ...",
    confirmQuestion: "ਕੀ ਤੁਸੀਂ ਜਾਰੀ ਰੱਖਣਾ ਚਾਹੁੰਦੇ ਹੋ? ਹਾਂ ਜਾਂ ਨਾ ਕਹੋ।",
    confidenceLow: "ਮੈਂ ਸੁਣਿਆ ਪਰ ਮੈਨੂੰ ਯਕੀਨ ਨਹੀਂ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵਾਰ ਦੁਬਾਰਾ ਕਹੋ।",
    helpText: "ਤੁਸੀਂ ਨੌਕਰੀ, ਮਜ਼ਦੂਰੀ, ਹਾਜ਼ਰੀ, ਬੀਮਾ, ਸਹਾਇਤਾ ਜਾਂ ਕੋਈ ਮੇਨੂ ਨੰਬਰ ਕਹਿ ਸਕਦੇ ਹੋ।",
    notUnderstood: "ਮੈਨੂੰ ਸਮਝ ਨਹੀਂ ਆਇਆ। ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਮੇਨੂ ਨੰਬਰ ਕਹੋ ਜਾਂ ਦੁਹਰਾਓ ਕਹੋ।",
    
    findJobs: "ਕੰਮ ਲੱਭੋ",
    myWorks: "ਮੇਰਾ ਕੰਮ",
    attendanceTracking: "ਹਾਜ਼ਰੀ ਟ੍ਰੈਕਿੰਗ",
    wagesManagement: "ਮਜ਼ਦੂਰੀ ਟ੍ਰੈਕਿੰਗ",
    healthInsurance: "ਸਿਹਤ ਬੀਮਾ",
    feedbackRating: "ਪ੍ਰਤੀਕਰਮ ਅਤੇ ਰੇਟਿੰਗ",
    chatSupport: "ਏਆਈ ਚੈਟ ਸਹਾਇਤਾ",
    hireLabour: "ਮਜ਼ਦੂਰ ਕਿਰਾਏ 'ਤੇ ਲਓ",
    manageJobs: "ਨੌਕਰੀਆਂ ਪ੍ਰਬੰਧਿਤ ਕਰੋ",
    rentalMarketplace: "ਕਿਰਾਇਆ ਬਾਜ਼ਾਰ",
    attendanceManagement: "ਹਾਜ਼ਰੀ ਪ੍ਰਬੰਧਨ",
    wagesManagementOwner: "ਮਜ਼ਦੂਰੀ ਪ੍ਰਬੰਧਨ",
    overview: "ਸੰਖੇਪ",
    userManagement: "ਉਪਭੋਗਤਾ ਪ੍ਰਬੰਧਨ",
    activeJobs: "ਸਰਗਰਮ ਨੌਕਰੀਆਂ",
    rentalSystem: "ਕਿਰਾਇਆ ਪ੍ਰਣਾਲੀ",
    globalAttendance: "ਗਲੋਬਲ ਹਾਜ਼ਰੀ",
    globalWages: "ਗਲੋਬਲ ਮਜ਼ਦੂਰੀ",
    profitsLedger: "ਮੁਨਾਫਾ ਅਤੇ ਵਹੀਖਾਤਾ",
    
    welcomeGreetings: {
      labour: "ਸ਼੍ਰਮਸੇਤੂ ਮਜ਼ਦੂਰ ਪੋਰਟਲ 'ਤੇ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ। ਕੰਮ ਲੱਭਣ ਲਈ 1 ਦਬਾਓ ਜਾਂ ਬੋਲੋ। ਮੇਰੇ ਕੰਮ ਲਈ 2। ਹਾਜ਼ਰੀ ਲਈ 3। ਮਜ਼ਦੂਰੀ ਲਈ 4। ਬੀਮੇ ਲਈ 5। ਪ੍ਰਤੀਕਰਮ ਲਈ 6। ਏਆਈ ਸਹਾਇਤਾ ਲਈ 7। ਜਾਂ ਮੇਨੂ ਦੁਹਰਾਉਣ ਲਈ 0 ਦਬਾਓ।",
      owner: "ਸ਼੍ਰਮਸੇਤੂ ਮਾਲਕ ਪੋਰਟਲ 'ਤੇ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ। ਮਜ਼ਦੂਰ ਕਿਰਾਏ 'ਤੇ ਲੈਣ ਲਈ 1 ਦਬਾਓ ਜਾਂ ਬੋਲੋ। ਨੌਕਰੀਆਂ ਪ੍ਰਬੰਧਿਤ ਕਰਨ ਲਈ 2। ਕਿਰਾਇਆ ਬਾਜ਼ਾਰ ਲਈ 3। ਹਾਜ਼ਰੀ ਲਈ 4। ਮਜ਼ਦੂਰੀ ਲਈ 5। ਬੀਮੇ ਲਈ 6। ਪ੍ਰਤੀਕਰਮ ਲਈ 7। ਚੈਟ ਸਹਾਇਤਾ ਲਈ 8। ਜਾਂ ਮੇਨੂ ਦੁਹਰਾਉਣ ਲਈ 0 ਦਬਾਓ।",
      admin: "ਸ਼੍ਰਮਸੇਤੂ ਐਡਮਿਨ ਪੋਰਟਲ 'ਤੇ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ। ਸੰਖੇਪ ਲਈ 1 ਦਬਾਓ ਜਾਂ ਬੋਲੋ। ਉਪਭੋਗਤਾ ਪ੍ਰਬੰਧਨ ਲਈ 2। ਸਰਗਰਮ ਨੌਕਰੀਆਂ ਲਈ 3। ਕਿਰਾਏ ਲਈ 4। ਹਾਜ਼ਰੀ ਲਈ 5। ਮਜ਼ਦੂਰੀ ਲਈ 6। ਬੀਮੇ ਲਈ 7। ਮੁਨਾਫੇ ਲਈ 8। ਪ੍ਰਤੀਕਰਮ ਲਈ 9। ਸਹਾਇਤਾ ਲਈ 10। ਜਾਂ ਮੇਨੂ ਦੁਹਰਾਉਣ ਲਈ 0 ਦਬਾਓ।"
    },
    spokenResponses: {
      findJobs: "ਉਪਲਬਧ ਨੌਕਰੀਆਂ ਖੋਲ੍ਹੀਆਂ ਜਾ ਰਹੀਆਂ ਹਨ।",
      myWorks: "ਤੁਹਾਡੇ ਸਰਗਰਮ ਕੰਮਾਂ ਦੀ ਸੂਚੀ ਖੋਲ੍ਹੀ ਜਾ ਰਹੀ ਹੈ।",
      attendance: "ਹਾਜ਼ਰੀ ਟ੍ਰੈਕਰ ਖੋਲ੍ਹਿਆ ਜਾ ਰਿਹਾ ਹੈ।",
      wages: "ਤੁਹਾਡੇ ਮਜ਼ਦੂਰੀ ਦੇ ਰਿਕਾਰਡ ਦਿਖਾਏ ਜਾ ਰਹੇ ਹਨ।",
      insurance: "ਬੀਮਾ ਡੈਸ਼ਬੋਰਡ ਖੋਲ੍ਹਿਆ ਜਾ ਰਿਹਾ ਹੈ।",
      feedback: "ਪ੍ਰਤੀਕਰਮ ਫਾਰਮ ਖੋਲ੍ਹਿਆ ਜਾ ਰਿਹਾ ਹੈ।",
      support: "ਏਆਈ ਚੈਟ ਸਹਾਇਤਾ ਖੋਲ੍ਹੀ ਜਾ ਰਹੀ ਹੈ।",
      rentals: "ਕਿਰਾਇਆ ਬਾਜ਼ਾਰ ਖੋਲ੍ਹਿਆ ਜਾ ਰਿਹਾ ਹੈ।",
      overview: "ਐਡਮਿਨ ਸਿਸਟਮ ਸਟੇਟਸ ਡੈਸ਼ਬੋਰਡ ਖੋਲ੍ਹਿਆ ਗਿਆ ਹੈ। ਵਰਤਮਾਨ ਵਿੱਚ 2 ਰਜਿਸਟਰਡ ਉਪਭੋਗਤਾ, 1 ਸਰਗਰਮ ਨੌਕਰੀ ਅਤੇ ਫਾਇਰਸਟੋਰ ਸਰਵਰ ਕਨੈਕਟਡ ਹੈ।",
      languageChanged: "ਭਾਸ਼ਾ ਬਦਲ ਕੇ ਪੰਜਾਬੀ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ।",
      notUnderstood: "ਮੈਨੂੰ ਸਮਝ ਨਹੀਂ ਆਇਆ। ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਮੇਨੂ ਨੰਬਰ ਕਹੋ ਜਾਂ ਦੁਹਰਾਓ ਕਹੋ।",
      repeatMenu: "ਮੇਨੂ ਵਿਕਲਪ ਦੁਹਰਾਏ ਜਾ ਰਹੇ ਹਨ।"
    }
  }
};
